### ISSUE TITLE
Infinite loop with a trailer record after nested group

### ISSUE THREAD

**Issue by pkan522** [mjones2219/FixedWidthFileUtils#2]
I'm getting stuck in an infinite loop when I try to deserialize a model with a trailer after a nested group.  It is easy to reproduce if you just add a trailer to your test model.

```
public class PositivePayFile
{
    [FixedField(0)]
    public FileHeader Header { get; set; }

    [FixedField(1)]
    public CheckGroup[] CheckGroups { get; set; }

    [FixedField(2)]
    public FileTrailer Trailer { get; set; }
}

public class FileTrailer
{
    [FixedField(0, 3)]
    public string Start => "*04";
}
```

**Comment by mikeacjones** [comment]
I’ll take a look this week.

**Comment by mikeacjones** [comment]
Quick question - did you define a `FixedObjectPattern` for the trailer? Sorry about the late reply, but with the end of the quarter coming up its been busy. @pkan522

**Comment by pkan522** [comment]
No problem, I tried with and without a FixedObjectPattern.

**Comment by mikeacjones** [comment]
@pkan522 Gotcha - thanks for the clarification. I'll be getting an environment set up this weekend to test (my work computer is a Mac these days) and I'm out of town right now, so to bootcamp it is.

**Comment by mikeacjones** [comment]
@pkan522 Would you mind posting the complete object structure you are serializing / deserializing? You can rename the objects / fields if any of it can't be shared publically, just want to make sure I have a matching structure.

**Comment by pkan522** [comment]
My actual file is large and more complex so I reproduced it with your test example:


`
        public class PositivePayFile
        {
            [FixedField(0)]
            public FileHeader Header { get; set; }

            [FixedField(1)]
            public CheckGroup[] CheckGroups { get; set; }

            [FixedField(2)]
            public FileTrailer Trailer { get; set; }
        }

        public class FileHeader
        {
            [FixedField(0, 3)]
            public string Start => "*03";

            [FixedField(1, 5)]
            public int BankID { get; set; }

            [FixedField(2, 15)]
            public long AccountNumber { get; set; }

            [FixedField(3, 1)]
            public int AlwaysZero => 0;
        }

        public class CheckRecord
        {
            [FixedField(0, 10, ' ', FixedFieldAlignment.Left, FixedFieldOverflowMode.Truncate)]
            public long CheckSerial { get; set; }

            [FixedField(1, 6)]
            [FixedFieldSerializer(typeof(WellsFargoDateSerializer))]
            public DateTime IssueDate { get; set; }

            [FixedField(2, 15)]
            public long AccountNumber { get; set; }

            [FixedField(3, 3)]
            public int TransactionCode => 320;

            [FixedField(4, 10)]
            [FixedFieldSerializer(typeof(DecimalToPenniesSerializer))]
            public decimal Amount { get; set; }

            private string _Payee;
            [FixedField(5, 41, ' ', FixedFieldAlignment.Left)]
            public string Payee
            {
                get => _Payee?.Trim();
                set => _Payee = value;
            }
        }

        public class CheckGroup
        {
            [FixedField(0)]
            public CheckRecord[] Records { get; set; }

            [FixedField(1)]
            public CheckGroupTrailer Trailer { get; set; }
        }

        [FixedObjectPattern("^&")]
        public class CheckGroupTrailer
        {
            [FixedField(0, 15, ' ', FixedFieldAlignment.Left)]
            public string Start => "&";

            [FixedField(1, 5)]
            public int RecordCount { get; set; }

            [FixedField(3, 10)]
            [FixedFieldSerializer(typeof(DecimalToPenniesSerializer))]
            public decimal TotalAmount { get; set; }

            [FixedField(2, 3, ' ')]
            [FixedField(4, 47, ' ')]
            public string Spacer => string.Empty;
        }

        [FixedObjectPattern("^%")]
        public class FileTrailer
        {
            [FixedField(0, 3, ' ', FixedFieldAlignment.Left)]
            public string Start { get; set; }
        }
`

**Comment by mikeacjones** [comment]
https://github.com/mikeacjones/FixedWidthFileUtils/tree/bug-2

**Comment by mikeacjones** [comment]
So this is only happening because I have an array of objects whose first field is another array of objects, so it never escapes out. I'll have to bubble that up correctly.

**Comment by mikeacjones** [comment]
@pkan522 Can you test the latest version? https://www.nuget.org/packages/FixedWidthFileUtils/1.3.1

**Comment by pkan522** [comment]
It is just throwing an IndexOutOfRangeException.  If I catch the exception, the file is not deserialized.

**Comment by mikeacjones** [comment]
Hmm. Do you have any arrays in the structure you're parsing where the array is empty? @pkan522

**Comment by pkan522** [comment]
There was an issue with how my file was formatted.  It is working.  Thanks!

**Comment by pkan522** [comment]
In one of my file formats, I do have an array that is usually empty (adjustments).  When the array is empty it results in an IndexOutOfRangeException.  Is there a way around this?

` -------------------------------------------------

        [FixedField(0)]
        public Header header { get; set; }

        [FixedField(1)]
        public List<DetailGroup> detailgroups { get; set; }

        [FixedField(2)]
        public List<Adjustment> adjustments { get; set; }

        [FixedField(3)]
        public Trailer trailer { get; set; }

        public class DetailGroup
        {
            [FixedField(0)]
            public Detail detail { get; set; }

            [FixedField(1)]
            public Addenda addenda { get; set; }

            [FixedField(2)]
            public List<Addenda2> addenda2s { get; set; }
        }
`

**Comment by mikeacjones** [comment]
Yes. I’d considered that already and planned to patch it.
