### ISSUE TITLE
Empty array field throws exception rather than returning an empty array or a null.

### ISSUE THREAD

**Issue by mikeacjones** [mjones2219/FixedWidthFileUtils#4]
When working with a structure like this:

```csharp
public class Order {
    public String ID { get; set; }
    public Items[] { get; set; }
}
```

If the file being deserialized contains an Order object with no Items, an exception is thrown.

**Comment by mikeacjones** [comment]
@pkan522 Mind checking out the branch `issue-4`, building it, and seeing if it works for you use cases? I don't have time to build out extensive scenarios right now, but definitely something I'll need to do since there are edge cases I've clearly missed. Or at least what would have been edge cases for the use case I built this for originally.

**Comment by pkan522** [comment]
Appreciate it!  It is working great on all the formats I've tested so far.  I'll let you know if I find anything.
